### ISSUE TITLE
Buggy dash testing in docker CI environment

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#39] opened 2016-10-28 16:47 UTC
# faulty tests

The following tests report errors in the docker test environment, using the build config from dash-ci.sh
## mpich
- [x] ArrayLargeStructTest (segfault)
- [x] HDF5 (See Issue #1)

4 Units
- [x] TeamLocalityTest.\* (Assert)

8 Units
- [x] DARTOnesidedTest.GetBlockingTwoBlocks (Assert)
## openmpi

3 Units
- [x] FillTest.TestAllItemsFilled (segfault)
- [x] ForEachTest.ForEachWithIndex (segfault)

4 Units
- [x] TeamLocalityTest.*(Assert)
- [x] MatrixTest.DelayedAlloc (segfault)

8 Units
- [x] TransformTest.ArrayGlobalPlusLocalBlocking

**Comment by fuchsto** [comment] 2016-10-30 07:27
Great effort! Working on fixes now.

**Comment by fmoessbauer** [comment] 2016-11-02 21:30
A full featured test environment for both mpich and openmpi tests using up to 4 units is provided in branch `bug-39-circleci-bugs`. The number of nodes can be increased, but then it's harder to find the failed tests as the output might interleave.

**Comment by fuchsto** [comment] 2016-11-03 10:59
@fmoessbauer How do I run the mpich container?

**Comment by fmoessbauer** [comment] 2016-11-03 11:31
Both containers are run in parallel if 2x 4 is configured in circleci. Otherwise they are build and executed sequentially.

If you want to run the container directly use the mpich dockerfile provided in dash/scripts/docker-testing/mpich

**Comment by fuchsto** [comment] 2016-11-03 17:23
Got it. It's merged to development now.

**Comment by fuchsto** [comment] 2016-11-03 17:34
CI currently passes with OpenMPI and MPICH:
https://circleci.com/gh/dash-project/dash/211#usage-queue/containers/1

The segfault is prevented for now.
Almost there! Some test cases are still deactivated.

**Comment by fuchsto** [comment] 2016-11-12 07:27
Added branch `bug-39-fill` for the last failing test case.

@fmoessbauer @fuerlinger @devreal 

Test case `FillTest.TestAllItemsFilled` only fails for: 
- OpenMPI
- Release mode
- element type with size of 8 bytes (works for int, float but fails for long, double)
- odd number of units

If two separate loops are used, each only writing every other element, the test passes:

``` c++
// segfaults:
for (index_t lt = 0; lt < nlocal; lt ++) {
  lbegin[lt] = value;
}

// works:
for (index_t lt = 0; lt < nlocal; lt += 2) {
  lbegin[lt] = value;
}
for (index_t lt = 1; lt < nlocal; lt += 2) {
  lbegin[lt] = value;
}
```

The variant using two passes with doubled striding also works fine when parallalizing the loops
with OpenMP.

Displacement unit of local addresses is okay, the local address range is not aligned, however.
This is due to the fact that `dart_team_memalloc_aligned` uses `MPI_BYTE` as underlying data type
instead of the actual value type like `MPI_DOUBLE`.

It actually even makes sense: as the defect only takes effect in Release mode, vectorization added
by the compiler for optimization might be an issue.
If the memory range is of type `double*` but aligned for `char` (= minimum alignment of 4 bytes),
vector operations might overlap and lead to invalid writes. Just an idea.

Perhaps the reason why it only fails for OpenMPI is that MPICH uses a wider minimum alignment.

I'm still scratching my head over this, but it's the only explanation I have at this point.
To falsify, I will check if the segfault can still be reproduced in a build with `sse` and `avx` disabled.
Otherwise, I will use gdb without debug symbols and observe the assembly instructions used to
access the memory range.

I'm merging the two-pass variant, it's a stable fix apparently, but we should clarify this behavior.

**Closed as completed** 2016-11-12 09:31 UTC
Labels: bug, support:CI
