### ISSUE TITLE
Tests hang using OpenMPI 2.0

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#63] opened 2016-11-05 15:18 UTC
The following tests hang when using openmpi 2.0. For testing and verification the new docker container `dashproject/ci:openmpi2` can be used. The container provides a openmpi 2.0 environment which is build from [sources](https://www.open-mpi.org/software/ompi/v2.0/).

It is also possible to ssh into the container on circleci and debug there.

# OpenMPI v2.0

## 2 Units
- [ ] SharedTest.AtomicAdd
- [ ] TransformTest.Array*

## 3 Units
- [x] CopyTest.AsyncLocalToGlobPtr

**Comment by fuchsto** [comment] 2016-11-05 16:04
@fmoessbauer I think some of these failed test are subsequent errors due to a defect in some test case that corrupts the runtime.
Can you please configure the containers such that each test suite is run in isolation using 

```
mpirun [ ... ] dash-test-mpi --gtest_filter="TheTestSuite.*"
```

... instead of a single execution of  `dash-test-mpi`?
I see no other way to locate the underlying bug.

**Comment by fuchsto** [comment] 2016-11-16 02:20
All clues lead to a defect in progress communication in OpenMPI:
https://github.com/open-mpi/ompi/issues/157

When an `MPI_Accumulate` is followed by an `MPI_Barrier` and OPAL progress threads are disabled, a deadlock occurs:

![openmpi2_opal_lock](https://cloud.githubusercontent.com/assets/37075/20332965/beed504c-abaf-11e6-9c66-b4f587f0f524.png)

In the `SharedTest.AtomicAdd` test case, all units add a local value to a shared global address using `MPI_Accumulate`. To wait for completion of all remote operations, units call `MPI_Barrier`.
If any unit X did not complete its `MPI_Accumulate` operation when any of its target units Y enters the barrier, progress communication stalls and unit X will never reach the barrier, in effect blocking execution forever.

The usage pattern in DART/DASH is fine. To fix these deadlock situations, OpenMPI has to be built with
support for MPI_THREAD_MULTIPLE  and OPAL pogress threads, but I didn't find a known good build configuration, yet.

And apparently, enabling progress threads leads to stability issues:
https://bugzilla.redhat.com/show_bug.cgi?id=1105902

Some additional remarks on progress threads and performance:
https://www.open-mpi.org/community/lists/users/2012/06/19588.php

Report on OpenMPI mailing list: https://www.mail-archive.com/search?l=devel@lists.open-mpi.org&q=subject:%22%5C%5BOMPI+devel%5C%5D+opal_progress%5C(%5C)+and+finalize%22&o=newest&f=1
Related issue at RedHat: https://bugzilla.redhat.com/attachment.cgi?id=904573&action=diff

**Comment by jgraciahlrs** [comment] 2016-11-16 08:44
We routinely use OpenMPI with MPI_THREAD_MULTIPLE, so I am surprised.

Could you run the following command 
   ompi_info --all --all       (note the double --all)
and send my the output by email. Also a small MPI-only test-case would be nice.

**Comment by devreal** [comment] 2016-11-16 08:56
Thanks for digging into this! Some remarks:

> All clues lead to a defect in progress communication in OpenMPI:
> open-mpi/ompi#157

If I understand this report correctly, the problem only occurs if `MPI_THREAD_MULTIPLE` is enabled. We currently do not enforce this since we only use MPI_Init. This is part of the MPI standard to allow for thread-concurrent MPI calls and we do not need this in development atm.

AFAIK, progress threads are an independent concept in OpenMPI to ensure progress even if the application thread(s) do not call MPI functions. Our OpenMPI installations are built without progress thread support but my colleague will build a version which has them enabled.

**Comment by fuchsto** [comment] 2016-11-16 11:09
No, that's for the OpenMPI defect. _Our_ defect occurs when `MPI_THREAD_MULTIPLE` is **not** enabled (see above) because the progress thread is blocked by the MPI barrier in this case. Otherwise the MPI process would stall but the progress thread continues and signals completion.
In some forum linked above - not the most reliable reference possibly - it is mentioned that OMPI progress should be enabled to avoid the deadlock situation in my use case. 

And of course the reason for this defect could be something totally different, I just didn't find a better explanation yet :/

**Comment by fuchsto** [comment] 2016-11-16 11:21
@jgraciahlrs Thank you a lot for looking into this, I'm not exactly an expert in OpenMPI configuration.

We can upload files here in the comments, the output of `ompi_info --all --all` is attached.
This is from a build with MPI_THREAD_MULTIPLE enabled and OMPI progress disabled, which didn't help.
[ompi_info_all_all.txt](https://github.com/dash-project/dash/files/594442/ompi_info_all_all.txt)

I will send you a minimal test case later.

**Comment by fuchsto** [comment] 2016-11-23 14:13
Test case `CopyTest.AsyncLocalToGlobPtr` is fixed for OpenMPI 2 in #152

**Comment by fuchsto** [comment] 2016-12-07 11:22
Also see my comments on a presumed bug in OpenMPI 2 in #184:
<https://github.com/dash-project/dash/issues/184#issuecomment-265416419>

**Comment by fuchsto** [comment] 2016-12-07 11:41
@jgraciahlrs 
This is one of the bugs in OpenMPI 2 that we stumbled upon:
https://github.com/open-mpi/ompi/issues/2530

After investing lots, **lots** of time into debugging our failing use cases, all of them could be tracked down to OpenMPI 2.

Another snapshot of a recent failing use case (#184 for details):

![dash-log-openmpi2-deadlock_annotated](https://cloud.githubusercontent.com/assets/37075/20964782/3c8d9984-bc73-11e6-97e4-3412119cc0ac.jpg)

**Comment by rkowalewski** [comment] 2016-12-07 14:35
@fuchsto @jgraciahlrs  I made some additional research. Actually, the problem does not only occur if we have multiple windows. OpenMPI-2 cannot make any progress if in a one-sided communication origin and target are the same rank. See https://github.com/open-mpi/ompi/issues/2538

I think there is at least a workaround. Even without MPI shared windows we can check if origin and target are the same. If that is the case we can directly access native (local) memory. I will test this.

**Comment by fuchsto** [comment] 2016-12-07 23:31
The last two defects reported in this issue are caused by this bug in OpenMPI-2, too.
For example, test case `SharedTest.AtomicAdd`:

![dash-log-openmpi2-deadlock-atomic_annotated](https://cloud.githubusercontent.com/assets/37075/20991172/43fb5778-bcdd-11e6-86ea-76e1ba619abd.jpg)

Same thing: unit 0 calls `MPI_Accumulate` on its own window (origin = target), unit 1 runs into a barrier, and execution locks up.

Even if grilling a surplus sausauge (get it?) for OpenMPI-2 is possible, this issue (#63) does not qualify as a bug.

Introduced new label "bug:external-issue".

**Comment by fuchsto** [comment] 2016-12-08 00:59
Retesting with nightly snapshot of OpenMPI-2, configured with

~~~
./configure --prefix=$HOME/opt/openmpi-2.0.1x \
            --enable-debug \
            --enable-mem-debug \
            --enable-mem-profile \
            --enable-pretty-print-stacktrace \
            --with-hwloc=internal
~~~

**Comment by ddiefenthaler** [comment] 2017-03-29 22:18
After lately nearly every test case was blocking for me,
I looked for a version of openmpi to build from sources and found `Open MPI: Version 2.1.0`.
This version appears to have fixed the blocking issue for me.

Currently every 5ths run of `dash-test-mpi` still aborts,
but this may also be a different issue as it just seem to happen in two test cases.
(Namely DARTLocalityTest.ExcludeLocalityDomain and TeamLocalityTest.SplitGroups)

**Comment by ddiefenthaler** [comment] 2017-03-29 22:53
As this is also seems true for `Open MPI: Version 2.0.2` I suggest to close this issue,
unless anybody else is still experiencing this issue.

For me this external bug looks like it is resolved.

**Comment by devreal** [comment] 2017-10-12 12:18
Fixed.

**Closed as completed by devreal** 2017-10-12 12:18 UTC
Labels: support:CI, backend:openmpi2, bug:external-issue
