### ISSUE TITLE
dash::Array storing the wrong team?

### ISSUE THREAD

**Issue by devreal** [dash-project/dash#353] opened 2017-03-31 14:46 UTC
I am still debugging #292 (with increasing desperation). I found the following strange behavior

```
TEST_F(ArrayTest, TeamSplit)
{
  auto & team_all = dash::Team::All();
  auto   ext_x    = team_all.size();

  if(team_all.size() < 2){
    SKIP_TEST();
  }
  if(!team_all.is_leaf()){
    LOG_MESSAGE("team is already splitted. Skip test");
    SKIP_TEST();
  }

  dash::barrier();

  LOG_MESSAGE("Splitting team ...");
  auto & myteam = team_all.split(2);
  LOG_MESSAGE("... Team split finished");

  dash::Array<double> array_a(ext_x, myteam);
  ASSERT_EQ_U(array_a.team(), myteam); // << this test fails!

  array_a.barrier();
  // Check if array is allocated
  ASSERT_NE_U(array_a.lbegin(), nullptr);
  team_all.barrier();
}
```

I added the check `ASSERT_EQ_U(array_a.team(), myteam)`, which surprisingly fails. My understanding is that `array.team()` should yield the team the array was created with so the check should  succeed. Looking through the code, I don't see what could go wrong there. Ideas?

UPDATE: The error I get is

```
[  ERROR   ] [UNIT 0] in /home/joseph/src/dash/dash/dash/test/container/ArrayTest.cc:225
      Expected: array_a.team()
      Which is: dash::Team(0)
To be equal to: myteam
      Which is: dash::Team(1.0)
```

**Comment by ddiefenthaler** [comment] 2017-04-01 01:54
I think I found the cause of this strange behaviour,
If I'm right it is related to PR #304 and through the implicit conversion from `dash::Team` to `dash::TeamSpec` now the wrong contructor gets called during the construction of `dash::Array` ([Code](https://github.com/dash-project/dash/blob/development/dash/include/dash/Array.h#L785)).

The fix for this should be simple.

**Comment by ddiefenthaler** [comment] 2017-04-01 02:38
Acctually it is not so simple, as the constructors of the different pattern types mismatch now.
For example the `CSRPattern` has no constructor which takes a `TeamSpec`.

@fuchsto Your feeling about the missing explicit was quite appropriate.

My best bet to fixing this issue is to revert PR #304 and just remove the default parameter definitions instead of the whole functions...
By the way who added those default parameters in the first hand? The `TeamSpec` should be dependend on the distribution which is not possible this way, if I got this right. For at least in line 336 of the deleted function it looks that way: [diff #304](https://github.com/dash-project/dash/pull/304/files#diff-da26b2a0973320ab6db84fc5fbadac63L336)

**Closed as completed** 2017-04-12 04:58 UTC
Labels: bug
