### ISSUE TITLE
dash::finalize really slow for a big matrix

### ISSUE THREAD

**Issue by dhinf** [dash-project/dash#520] opened 2018-04-12 08:37 UTC
Since commit https://github.com/dash-project/dash/commit/ee6e92bd1cedc11e335072fb410271a85516e021 dash::finalize takes really long to deallocate the memory. 
Tested with:
ex.02.matrix.halo.heat_equation and 24 units
Matrix size:20000 x 20000
100 iterations

compile flags application: -O3 -std=c++14 -march=native

System:
Taurus (Dresden)
Haswell partition
one node with 24 cores
modules:  gcc/7.1.0;  openmpi/3.0.0-gnu7.1

-DCMAKE_BUILD_TYPE=Release \
                        -DENVIRONMENT_TYPE=default \
                        -DDART_IMPLEMENTATIONS=mpi \
                        -DENABLE_THREADSUPPORT=ON \
                        -DENABLE_DEV_COMPILER_WARNINGS=OFF \
                        -DENABLE_EXT_COMPILER_WARNINGS=OFF \
                        -DENABLE_LT_OPTIMIZATION=OFF \
                        -DENABLE_ASSERTIONS=ON \
                        \
                        -DENABLE_SHARED_WINDOWS=ON \
                        -DENABLE_DYNAMIC_WINDOWS=ON \
                        -DENABLE_UNIFIED_MEMORY_MODEL=ON \
                        -DENABLE_DEFAULT_INDEX_TYPE_LONG=ON \
                        \
                        -DENABLE_LOGGING=OFF \
                        -DENABLE_TRACE_LOGGING=OFF \
                        -DENABLE_DART_LOGGING=OFF \
                        \
                        -DENABLE_LIBNUMA=ON \
                        -DENABLE_LIKWID=OFF \
                        -DENABLE_HWLOC=OFF \
                        -DENABLE_PAPI=OFF \
                        -DENABLE_MKL=OFF \
                        -DENABLE_BLAS=OFF \
                        -DENABLE_LAPACK=OFF \
                        -DENABLE_SCALAPACK=OFF \
                        -DENABLE_PLASMA=OFF \
                        -DENABLE_HDF5=OFF \
                        \
                        -DBUILD_EXAMPLES=OFF \
                        -DBUILD_TESTS=OFF \
                        -DBUILD_DOCS=OFF \

**Comment by devreal** [comment] 2018-04-12 08:39
What was the system? How many nodes? Which MPI?

**Comment by devreal** [comment] 2018-04-12 14:37
Can you run with DART logging turned on to see whether this is one long operation or many small operations? My first suspicion was the deregistration of memory from the IB device (not sure that is required after all, registration can take ages depending on the size) but the memory should not be registered in your case...

**Comment by devreal** [comment] 2018-04-16 12:53
I tried to reproduce this: on the Cray system I don't see any issue with `finalize` when not using dynamic windows. With dynamic/shared memory windows there seem to be progress issues (pending further investigation). On our Linux cluster and Open MPI I see progress issues as well. 

@dhinf Can you please try to disable dynamic/shared memory windows to see whether that has any effect?

**Comment by dhinf** [comment] 2018-04-23 14:32
Didn't changed anything.

**Comment by dhinf** [comment] 2018-04-24 07:38
Actually, the commits before became slower when turning off dynamic/shared windows. So that might not be the problem.

**Comment by devreal** [comment] 2018-04-24 07:44
With #521 merged, could you please re-run and paste the DART debug output here?

**Comment by devreal** [comment] 2018-04-27 11:55
I was able to reproduce this on Taurus and (as I originally suspected) *it has to do with shared/dynamic windows*. Here is what I see: 

1) With dynamic windows enabled and shared memory windows disabled the performance is good. 
2) With dynamic windows and shared windows enabled, the performance is low.
3) With dynamic windows and shared windows disabled, the performance is low. 

I see that in both 2) and 3) the pointers are 8-byte aligned instead of 16 byte as in 1). That might account for the low computational performance (but needs some more investigation). A cause for the high allocation/deallocation delays may be the allocation of shared memory (as done by Open MPI with >1 processes per node) and some page-wise operations (IIRC, mmap nulls the memory but I'm not sure). In any case, none of that takes place with dynamic windows only, where memory is allocated through `MPI_Alloc_mem` and attached to the window, no shared memory is allocated and nulled/registered with the IB device.

Finally, the reason the commit you mentioned (which is only half of what was merged back then) triggers this is that before this commit we turned off shared memory windows because of broken memory alignment in Open MPI and only enabled dynamic windows by default. After this commit, shared memory windows are turned off only for Open MPI < 2.1.0 (as that was where the alignment was fixed). 

I any case, that is a problem with (Open) MPI and not with DART/DASH.

**Closed as completed** 2018-04-27 11:56 UTC
Labels: performance
