### ISSUE TITLE
Uneven distribution in BlockPattern: empty units

### ISSUE THREAD

**Issue by devreal** [dash-project/dash#425] opened 2017-07-28 13:30 UTC
Consider the following code snippet: 

```
#include <libdash.h>

using element_t = unsigned char;
using Array_t   = dash::NArray<element_t, 2>;

int main(int argc, char **argv)
{
  dash::init(&argc, &argv);

  size_t sizex = 10;
  size_t sizey = 10;

  // Prepare grid
  dash::TeamSpec<2> ts;
  dash::SizeSpec<2> ss(sizex, sizey);
  dash::DistributionSpec<2> ds(dash::BLOCKED, dash::NONE);
  dash::Pattern<2> pattern(ss, ds, ts);

  std::cout << "[" << dash::myid() << "] local extents = (" << pattern.local_extent(0) << ", " << pattern.local_extent(1) << ")" << std::endl;

  dash::finalize();
}
```

I am observing a strange distribution of the `(10, 10)` two-dimensional array: 

5 units:
```
$ mpirun -n 5 ./dash_matrix_dist
[0] local extents = (2, 10)
[1] local extents = (2, 10)
[3] local extents = (2, 10)
[2] local extents = (2, 10)
[4] local extents = (2, 10)
```
5 units:
```
$ mpirun -n 6 ./dash_matrix_dist
[1] local extents = (2, 10)
[3] local extents = (2, 10)
[4] local extents = (2, 10)
[0] local extents = (2, 10)
[2] local extents = (2, 10)
[5] local extents = (0, 10)
```
--> Notice the unit with 0 elements. I would expect a distribution of `2,2,2,2,1,1` to avoid empty units.

10 units:
```
$ mpirun -n 10 ./dash_matrix_dist
[0] local extents = (1, 10)
[5] local extents = (1, 10)
[9] local extents = (1, 10)
[2] local extents = (1, 10)
[4] local extents = (1, 10)
[6] local extents = (1, 10)
[1] local extents = (1, 10)
[7] local extents = (1, 10)
[3] local extents = (1, 10)
[8] local extents = (1, 10)
```

Also notice the load imbalance with 4 units:
```
$ mpirun -n 4 ./dash_matrix_dist
[0] local extents = (3, 10)
[1] local extents = (3, 10)
[2] local extents = (3, 10)
[3] local extents = (1, 10)
```
a distribution of `3,3,2,2` seems to be more suitable, even though this is a less severe issue than empty units.

**Comment by fuerlinger** [comment] 2017-07-28 17:54
This is by design. Even in 1D, `dash::BLOCKED` means: determine the blocksize as `ceil(nelem/nunits)` and distribute a block to each unit, except for the last one which gets the rest (which might be zero). Doing it this way is in line with what is used in other data distribution specifications. In OpenMP a `static` loop scheduling clause does the same type  of partitioning of loop iterations into equal sized blocks.

We could certainly add a `dash::BALANCED` distribution (or something like that) but currently, I think, this is not supported in DASH.

**Comment by fuchsto** [comment] 2017-07-28 19:10
What @fuerlinger said.
The conceptual problem with "dash::BALANCED" is that it would have to be supported by any pattern type. This is not possible *with the current spec of the Pattern concept* and will be addressed in ... 2-3 weeks in refined Pattern concepts.

**Comment by devreal** [comment] 2017-08-07 15:56
After I lost yet another large-scale job to this (due to a `dash::exception::OutOfRange` exception when checking the coordinates of the first local row, duh!) I have to comment on this again. I first thought that I can live with it, but: 

1. From a usability point of view this is catastrophic. I think it is safe to assume that the user will choose a problem size suitable for the number of units he allocates. Even if the problem size could well be distributed across all units, he might end up with an OOR just because the problem size was off by one. So he'd have to check whether a unit might be empty (most likely in several places because the unit cannot  just sit in `dash::finalize`), which increases code complexity and is simply not intuitive. Without cluttering the code with these checks, strong scaling studies become really cumbersome. 

2. The argument that this is the way workload distribution is done in OpenMP is not valid imo. The standard is rather unclear here and leaves room for implementation specifics: 
> When no `chunk_size` is specified, the iteration space is divided into chunks that are *approximately* equal in size, and at most one chunk is distributed to each thread. The size of the chunks is unspecified in this case.

3. It's just a waste of resources. I don't think we can easily justify leaving processes (or whole nodes, if we talk about multi-threading) idling. That is a flawed design decision.

Having said that: 

> Even in 1D, `dash::BLOCKED` means: determine the blocksize as `ceil(nelem/nunits)` and distribute a block to each unit, except for the last one which gets the rest (which might be zero).

What prevents us from determining the block size as `floor(nelem/nunits)` and assigning the remaining `r` elements to the first `r` units (one-by-one and in a way such that block are still contiguous of course)? My understanding is that `dash::BLOCKED` just means that each unit has at most one block in this dimension and we cannot enforce equal-sized blocks anyway (due to remainders).

**Closed as completed** 2018-09-20 11:39 UTC
Labels: invalid, module:narray
